Repository bounswe/bounswe2025group6, pull requests merged in 2025-02, with the labels that each got.

#1 Add issue rules
  Issue/issue_example.md
  Issue/issue_rules.md
Labels: type: documentation, priority: high, effort: medium, status: needs review

#37 Added a basic readme
  README.md
Labels: priority: low, effort: low, status: needs review

#40 README is updated
  README.md
Labels: type: documentation, type: improvement, effort: low, status: needs review
